environment: arch # Change to debian for Debian or Ubuntu.
categories:
  - name: setup
    items:
      - github-ssh-keys
  - name: cli-programming
    items:
      - github-cli
  - name: programming-env
    items:
      - javascript
      - haskell
      - idris
      - rust
  - name: editors
    items:
      - zed
      - cursor
  - name: agents
    items:
      - codex
      - claude-code
      - cursor-agent-cli
      - pi
      - opencode
      - grok-build
      - muse-spark
  - name: personal-agents
    items:
      - grok-bot
  - name: music
    items:
      - spotify
  - name: productivity
    items:
      - obsidian
      - todoist
